import { Platform, StatusBar, StyleSheet } from 'react-native';
import {
  BOTTOM_NAV_HORIZONTAL_PADDING,
  BOTTOM_NAV_INDICATOR_HEIGHT,
  BOTTOM_NAV_INDICATOR_WIDTH,
} from '../constants/appConstants';

function getStyles(colors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    skeletonBlock: {
      overflow: 'hidden',
    },
    skeletonBlockBase: {
      backgroundColor: colors.surfaceAlt,
    },
    skeletonBlockAccent: {
      backgroundColor: colors.primaryLight,
    },
    skeletonScreenOverlay: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      zIndex: 50,
    },
    skeletonViewport: {
      position: 'absolute',
      left: 0,
      right: 0,
      backgroundColor: colors.background,
    },
    skeletonViewportScroll: {
      flex: 1,
    },
    skeletonViewportContent: {
      paddingTop: 4,
    },
    skeletonInitialScreen: {
      flex: 1,
      paddingHorizontal: 24,
      paddingTop: 32,
      paddingBottom: 32,
    },
    skeletonInitialBrand: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 28,
    },
    skeletonInitialCard: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 24,
      padding: 22,
      marginBottom: 22,
    },
    skeletonInitialList: {
      gap: 14,
    },
    skeletonInitialListRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 22,
      paddingHorizontal: 18,
      paddingVertical: 16,
    },
    skeletonCard: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 22,
      padding: 18,
      marginBottom: 16,
    },
    skeletonCardSubtle: {
      backgroundColor: colors.inputBg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 20,
      padding: 16,
    },
    skeletonPillRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 18,
    },
    skeletonMiniPill: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 11,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.surface,
    },
    skeletonSplitRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 12,
    },
    skeletonSplitCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 20,
      padding: 18,
    },
    skeletonGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 14,
    },
    skeletonGridCard: {
      width: '47.5%',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 20,
      padding: 16,
      minHeight: 132,
    },
    skeletonPatientsHero: {
      paddingTop: 8,
    },
    skeletonFilterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 18,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginBottom: 16,
    },
    skeletonPatientHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    skeletonPatientIdentity: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: 12,
    },
    skeletonListGroup: {
      gap: 12,
    },
    skeletonListRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
      paddingTop: 12,
    },
    skeletonAgendaTop: {
      paddingTop: 8,
      marginBottom: 18,
    },
    skeletonMonthRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 18,
      paddingHorizontal: 6,
    },
    skeletonDayRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 10,
      marginBottom: 18,
    },
    skeletonDayPill: {
      flex: 1,
      minWidth: 48,
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 18,
      paddingVertical: 12,
      paddingHorizontal: 6,
    },
    skeletonAgendaCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 22,
      padding: 16,
      marginBottom: 14,
    },
    skeletonAgendaTime: {
      width: 44,
      alignItems: 'center',
      marginRight: 14,
      paddingTop: 4,
    },
    skeletonAgendaDivider: {
      width: 2,
      alignSelf: 'stretch',
      borderRadius: 1,
      backgroundColor: colors.borderLight,
      marginRight: 14,
    },
    skeletonAgendaActions: {
      flexDirection: 'row',
      gap: 10,
    },
    skeletonAccordionCard: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 22,
      padding: 16,
      marginBottom: 14,
    },
    skeletonAccordionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    skeletonAccordionTitle: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    skeletonMetricsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 18,
    },
    skeletonMetricsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 14,
    },
    skeletonMetricCol: {
      flex: 1,
      alignItems: 'center',
    },
    skeletonMenuRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginBottom: 12,
    },
    skeletonMenuLeading: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      marginRight: 12,
    },
    skeletonChatBubble: {
      maxWidth: '82%',
      borderRadius: 22,
      paddingHorizontal: 18,
      paddingVertical: 16,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    skeletonChatBubbleAi: {
      alignSelf: 'flex-start',
      backgroundColor: colors.surface,
    },
    skeletonChatBubbleUser: {
      alignSelf: 'flex-end',
      backgroundColor: colors.primaryLight,
    },
    onboardingOverlay: {
      flex: 1,
      backgroundColor: colors.background,
    },
    onboardingContainer: { flex: 1, paddingHorizontal: 24, paddingTop: 8, paddingBottom: 24 },
    onboardingHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8, marginBottom: 14 },
    onboardingBrandRow: { flexDirection: 'row', alignItems: 'center' },
    onboardingBrandLogo: { width: 52, height: 52, marginRight: -2 },
    onboardingBrandText: { color: colors.primary, fontSize: 30, fontWeight: '800', letterSpacing: -0.5 },
    onboardingSkipBtn: { minHeight: 36, justifyContent: 'center', paddingHorizontal: 8 },
    onboardingSkipText: { color: colors.textSecondary, fontSize: 14, fontWeight: '700' },
    onboardingCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.borderLight,
      paddingHorizontal: 22,
      paddingTop: 26,
      paddingBottom: 20,
      justifyContent: 'center',
    },
    onboardingStepPill: {
      alignSelf: 'center',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: colors.inputBg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      marginBottom: 18,
    },
    onboardingStepPillText: {
      color: colors.textSecondary,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    onboardingIconCircle: {
      width: 98,
      height: 98,
      borderRadius: 49,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 20,
      alignSelf: 'center',
    },
    onboardingTitle: { color: colors.text, fontSize: 28, fontWeight: '800', textAlign: 'center', marginBottom: 12 },
    onboardingDescription: { color: colors.textSecondary, fontSize: 15, lineHeight: 24, textAlign: 'center', marginBottom: 20 },
    onboardingBulletList: { gap: 10 },
    onboardingBulletRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBg,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.borderLight,
      paddingVertical: 10,
      paddingHorizontal: 12,
    },
    onboardingBulletText: { color: colors.text, fontSize: 13, fontWeight: '600', marginLeft: 8, flex: 1, lineHeight: 18 },
    onboardingFooter: { paddingTop: 18 },
    onboardingDotsRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: 18 },
    onboardingDot: {
      width: 10,
      height: 10,
      borderRadius: 999,
      backgroundColor: colors.border,
      borderWidth: 1,
      borderColor: colors.border,
      marginHorizontal: 4,
    },
    onboardingDotActive: { width: 26, borderRadius: 999 },
    onboardingButtonsRow: { flexDirection: 'row', alignItems: 'center' },
    onboardingGhostButton: {
      flex: 1,
      height: 50,
      borderRadius: 25,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
      backgroundColor: colors.surface,
    },
    onboardingGhostButtonText: { color: colors.textSecondary, fontSize: 15, fontWeight: '700' },
    onboardingPrimaryButton: {
      flex: 1,
      height: 50,
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.primary,
      paddingHorizontal: 16,
    },
    onboardingPrimaryButtonFull: { flex: 1.5 },
    onboardingPrimaryButtonText: { color: '#FFF', fontSize: 15, fontWeight: '800' },
    headerFixoLogin: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 80, marginBottom: -30 },
    logo: { width: 80, height: 80, marginRight: -8 },
    logoText: { color: colors.primary, fontSize: 44, fontWeight: '700', letterSpacing: -0.5 },
    textBlue: { color: colors.primary },
    content: { flex: 1, paddingHorizontal: 24 },
    contentForgot: { paddingTop: 18, paddingBottom: 12 },
    telaWrapper: { flex: 1, marginTop: 20 },
    placeholderTitle: { height: 22, marginBottom: 20 },
    selectionTitle: { color: colors.text, fontSize: 18, textAlign: 'center', marginBottom: 30, fontWeight: '600' },
    userCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: 12, padding: 16, marginBottom: 24, height: 85 },
    avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.background, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#3B82F6' },
    avatarText: { color: colors.text, fontSize: 16, fontWeight: '700' },
    userInfo: { flex: 1, marginLeft: 16 },
    userName: { color: colors.text, fontSize: 16, fontWeight: '600' },
    userId: { color: colors.textSecondary, fontSize: 13, marginTop: 2 },
    editContainer: { backgroundColor: colors.surface, borderRadius: 16, padding: 20, marginBottom: 24, alignItems: 'center' },
    avatarLarge: { width: 70, height: 70, borderRadius: 35, backgroundColor: colors.background, justifyContent: 'center', alignItems: 'center', marginBottom: 25, borderWidth: 2, borderColor: '#3B82F6' },
    avatarTextLarge: { color: colors.text, fontSize: 24, fontWeight: '700' },
    profilePhotoEditorBlock: { width: '100%', alignItems: 'center', marginBottom: 18 },
    editableAvatarButton: { width: 96, height: 96, borderRadius: 48, marginBottom: 12 },
    avatarEditBadge: {
      position: 'absolute',
      right: -2,
      bottom: -2,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: '#3B82F6',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: colors.surface,
    },
    profilePhotoHint: { color: colors.textSecondary, fontSize: 12, textAlign: 'center', lineHeight: 18, marginBottom: 12 },
    profilePhotoActionsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', flexWrap: 'wrap', gap: 10 },
    profilePhotoActionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(59,130,246,0.25)',
      paddingVertical: 9,
      paddingHorizontal: 14,
    },
    profilePhotoActionText: { color: colors.primary, fontSize: 13, fontWeight: '700', marginLeft: 7 },
    profilePhotoRemoveBtn: { backgroundColor: 'rgba(239, 68, 68, 0.12)', borderColor: 'rgba(239, 68, 68, 0.22)' },
    profilePhotoRemoveText: { color: '#EF4444', fontSize: 13, fontWeight: '700', marginLeft: 7 },
    inputGroup: { width: '100%', marginBottom: 15 },
    inputLabel: { color: colors.primary, fontSize: 10, fontWeight: '800', marginBottom: 5, marginLeft: 2 },
    editInputWrapper: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.background, borderRadius: 8, paddingHorizontal: 12, height: 45, borderWidth: 1, borderColor: colors.border },
    editInput: { flex: 1, color: colors.text, fontSize: 14 },
    btnTrocar: { borderWidth: 1, borderColor: colors.border, borderRadius: 20, paddingVertical: 6, paddingHorizontal: 16 },
    btnTrocarText: { color: colors.textSecondary, fontSize: 13, fontWeight: '500' },
    inputContainer: { marginBottom: 24, height: 56 },
    inputWrapper: { flex: 1, flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderRadius: 8, paddingHorizontal: 16, position: 'relative' },
    input: { flex: 1, fontSize: 16, height: '100%', textAlignVertical: 'center' },
    iconRow: { flexDirection: 'row', alignItems: 'center' },
    iconButton: { marginLeft: 12 },
    btnEntrar: { backgroundColor: '#3B82F6', height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
    btnEntrarText: { color: '#FFF', fontSize: 16, fontWeight: '600' },
    loginButtonDisabled: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderLight },
    loginButtonTextDisabled: { color: colors.textSecondary },
    btnEsqueci: { backgroundColor: colors.avatarBg, height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
    btnEsqueciText: { color: colors.primaryText, fontSize: 16, fontWeight: '500' },
    footerText: { color: colors.textSecondary, fontSize: 13, textAlign: 'center', lineHeight: 20, marginTop: 10, marginBottom: 20 },
    footerLink: { color: colors.text, fontWeight: '700' },
    forgotScreenContainer: { flex: 1, paddingTop: 6, paddingBottom: 10 },
    forgotTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    forgotBrandPill: { flexDirection: 'row', alignItems: 'center' },
    forgotBrandLogo: { width: 42, height: 42, marginRight: -3 },
    forgotBrandText: { color: colors.primary, fontSize: 28, fontWeight: '800', letterSpacing: -0.4 },
    forgotCloseButton: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderLight },
    forgotScrollContent: { paddingBottom: 24 },
    forgotHeroCard: { height: 370, borderRadius: 42, backgroundColor: '#DCEBFF', overflow: 'hidden', marginBottom: 28, justifyContent: 'center', alignItems: 'center', position: 'relative' },
    forgotHeroShapeOne: { position: 'absolute', width: 260, height: 260, borderRadius: 130, backgroundColor: 'rgba(59, 130, 246, 0.16)', top: -40, right: -60 },
    forgotHeroShapeTwo: { position: 'absolute', width: 220, height: 220, borderRadius: 110, backgroundColor: 'rgba(37, 99, 235, 0.12)', bottom: -40, left: -40 },
    forgotHeroBadge: { position: 'absolute', top: 24, left: 24, flexDirection: 'row', alignItems: 'center', backgroundColor: '#3B82F6', paddingVertical: 8, paddingHorizontal: 14, borderRadius: 999 },
    forgotHeroBadgeText: { color: '#FFF', fontSize: 12, fontWeight: '700', marginLeft: 8 },
    forgotHeroLogoMain: { width: 180, height: 180, marginBottom: 16 },
    forgotHeroMiniCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', paddingVertical: 12, paddingHorizontal: 18, borderRadius: 18, borderWidth: 1, borderColor: 'rgba(59, 130, 246, 0.18)' },
    forgotHeroMiniCardText: { color: '#1C1C1E', fontSize: 14, fontWeight: '700', marginLeft: 10 },
    forgotTitle: { color: colors.text, fontSize: 26, fontWeight: '800', lineHeight: 32, marginBottom: 18 },
    forgotInfoBlock: { marginBottom: 14 },
    forgotInfoText: { color: colors.textSecondary, fontSize: 16, lineHeight: 26 },
    forgotInfoStrong: { color: colors.text, fontWeight: '800' },
    forgotHelperText: { color: colors.textSecondary, fontSize: 15, lineHeight: 24 },
    forgotPrimaryButton: { backgroundColor: colors.primary, height: 56, borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginTop: 'auto' },
    forgotPrimaryButtonText: { color: '#FFF', fontSize: 16, fontWeight: '800' },
    btnVoltarSimples: { alignItems: 'center', marginTop: 10 },
    btnVoltarSimplesText: { color: colors.textSecondary, fontSize: 14 },
    modalOverlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' },
    modalContent: { backgroundColor: colors.surface, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, alignItems: 'center', width: '100%', maxHeight: '90%' },
    modalHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', alignItems: 'center', marginBottom: 20 },
    modalHandle: { width: 40, height: 4, backgroundColor: colors.border, borderRadius: 2, marginBottom: 20 },
    modalTitle: { color: colors.text, fontSize: 18, fontWeight: '700', marginBottom: 12 },
    modalMessage: { color: colors.textSecondary, fontSize: 14, textAlign: 'center', lineHeight: 20, marginBottom: 30 },
    btnModalPrincipal: { backgroundColor: '#3B82F6', width: '100%', height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', marginBottom: 12 },
    btnModalSecundario: { width: '100%', height: 56, justifyContent: 'center', alignItems: 'center' },
    btnModalSecundarioText: { color: colors.primary, fontSize: 16, fontWeight: '600' },
    btnModalSecundarioDanger: { width: '100%', height: 52, borderRadius: 26, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(239, 68, 68, 0.12)', borderWidth: 1, borderColor: 'rgba(239, 68, 68, 0.2)' },
    btnModalSecundarioDangerText: { color: '#EF4444', fontSize: 15, fontWeight: '700' },
    homeContainer: { flex: 1, backgroundColor: colors.background },
    homeScroll: { flex: 1, paddingHorizontal: 24 },
    homeHeaderFixo: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 24, marginTop: Platform.OS === 'android' ? Math.max((StatusBar.currentHeight || 0) + 10, 34) : 25, marginBottom: 25 },
    headerLogoRow: { flexDirection: 'row', alignItems: 'center' },
    headerLogo: { width: 60, height: 60, marginRight: -2 },
    headerLogoText: { color: colors.primary, fontSize: 32, fontWeight: '700', letterSpacing: -0.5 },
    headerRight: { flexDirection: 'row', alignItems: 'center' },
    headerAvatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.avatarBg, justifyContent: 'center', alignItems: 'center', marginRight: 15 },
    headerAvatarText: { color: colors.text, fontWeight: 'bold', fontSize: 16 },
    searchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: 25, paddingHorizontal: 15, height: 55, marginBottom: 25 },
    searchInput: { flex: 1, color: colors.text, marginLeft: 10, fontSize: 16 },
    greetingCard: { backgroundColor: colors.surface, borderRadius: 15, padding: 25, marginBottom: 18 },
    greetingTitle: { color: colors.text, fontSize: 24, fontWeight: 'bold', marginBottom: 8 },
    greetingSub: { color: colors.textSecondary, fontSize: 14 },
    shortcutScroll: { marginBottom: 22 },
    sectionTitle: { color: colors.textSecondary, fontSize: 15, fontWeight: '600', marginBottom: 20 },
    statsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 30 },
    statBox: { flex: 1, flexDirection: 'column', alignItems: 'flex-start' },
    statHeaderCentered: { flexDirection: 'row', alignItems: 'center', marginBottom: 5 },
    statValue: { color: colors.text, fontSize: 32, fontWeight: 'bold', marginLeft: 10 },
    statLabel: { color: colors.textSecondary, fontSize: 13, fontWeight: '500', marginTop: 2 },
    gridContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', paddingBottom: 20 },
    gridItem: { width: '48%', backgroundColor: colors.surface, borderRadius: 18, paddingVertical: 30, alignItems: 'center', marginBottom: 15 },
    gridItemText: { color: colors.text, fontWeight: '600', marginTop: 12, fontSize: 14, textAlign: 'center' },
    bottomNavShell: { width: '100%', alignSelf: 'stretch', backgroundColor: colors.navBg },
    bottomNavBar: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', backgroundColor: colors.navBg, borderTopWidth: 1, borderTopColor: colors.navBorder, paddingTop: 12, paddingBottom: 22, paddingHorizontal: BOTTOM_NAV_HORIZONTAL_PADDING, width: '100%', alignSelf: 'stretch', position: 'relative', overflow: 'visible' },
    bottomNavAndroidSpacer: { width: '100%', alignSelf: 'stretch', backgroundColor: colors.androidNavSpacer },
    navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', position: 'relative', minWidth: 0, paddingTop: 8, paddingBottom: 4 },
    navItemText: { fontSize: 12, fontWeight: '500', marginTop: 4, textAlign: 'center' },
    navActiveIndicatorSlider: {
      position: 'absolute',
      left: 0,
      top: 0,
      width: BOTTOM_NAV_INDICATOR_WIDTH,
      height: BOTTOM_NAV_INDICATOR_HEIGHT,
      borderRadius: 1,
      backgroundColor: colors.primary,
    },
    pageTitleCentralized: { color: colors.text, fontSize: 24, fontWeight: '700', textAlign: 'center', marginBottom: 8 },
    pageSubtitleCentralized: { color: colors.textSecondary, fontSize: 14, textAlign: 'center', marginBottom: 18 },
    monthSelectorRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 },
    monthSelectorText: { color: colors.text, fontSize: 16, fontWeight: '700' },
    monthNavButton: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderLight },
    agendaHeaderTopRow: { marginTop: 10, marginBottom: 14 },
    agendaHeaderTextCol: { width: '100%' },
    agendaMonthSummaryCard: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.borderLight, padding: 18, marginBottom: 18 },
    agendaMonthSummaryTitle: { color: colors.textSecondary, fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8 },
    agendaMonthSummaryValue: { color: colors.text, fontSize: 24, fontWeight: '800', marginBottom: 6 },
    agendaMonthSummaryText: { color: colors.textSecondary, fontSize: 13, lineHeight: 20 },
    agendaCalendarWrapper: { marginBottom: 20 },
    agendaDayPill: { width: 62, height: 76, backgroundColor: colors.surface, borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginRight: 12, borderWidth: 1, borderColor: colors.borderLight },
    agendaDayPillActive: { backgroundColor: '#3B82F6', borderColor: '#3B82F6' },
    agendaDayWeekText: { color: colors.textSecondary, fontSize: 12, fontWeight: '600', marginBottom: 6 },
    agendaDayNumberText: { color: colors.text, fontSize: 20, fontWeight: '700' },
    agendaDailyHeader: { marginBottom: 16 },
    agendaDailyDateText: { color: colors.text, fontSize: 18, fontWeight: '700', marginBottom: 4 },
    agendaDailyCountText: { color: colors.textSecondary, fontSize: 13 },
    agendaEmptyCard: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.borderLight, padding: 24, alignItems: 'center', marginBottom: 18 },
    agendaCard: { backgroundColor: colors.surface, borderRadius: 16, padding: 16, marginBottom: 14, flexDirection: 'row', alignItems: 'center' },
    agendaTimeCol: { width: 48, alignItems: 'center' },
    agendaTimeHour: { color: colors.text, fontSize: 22, fontWeight: '700' },
    agendaTimeMin: { color: colors.textSecondary, fontSize: 14, marginTop: -2 },
    agendaVerticalDivider: { width: 4, height: '100%', borderRadius: 3, marginHorizontal: 14 },
    agendaDetailsCol: { flex: 1 },
    agendaPatientName: { color: colors.text, fontSize: 16, fontWeight: '700', marginBottom: 6 },
    agendaTypeRow: { flexDirection: 'row', alignItems: 'center' },
    agendaTypeText: { color: colors.textSecondary, fontSize: 13, marginLeft: 6 },
    agendaObservationText: { color: colors.textSecondary, fontSize: 12, lineHeight: 18, marginTop: 8 },
    agendaActionRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8, marginTop: 12 },
    agendaActionBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primaryLight, borderRadius: 999, borderWidth: 1, borderColor: 'rgba(59,130,246,0.25)', paddingVertical: 7, paddingHorizontal: 12 },
    agendaActionText: { color: colors.primary, fontSize: 12, fontWeight: '700', marginLeft: 6 },
    agendaDeleteBtn: { backgroundColor: 'rgba(239, 68, 68, 0.12)', borderColor: 'rgba(239, 68, 68, 0.2)' },
    agendaDeleteText: { color: '#EF4444', fontSize: 12, fontWeight: '700', marginLeft: 6 },
    agendaStatusBadge: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 999 },
    agendaStatusText: { fontSize: 12, fontWeight: '700' },
    agendaFab: { position: 'absolute', right: 24, bottom: 104, width: 60, height: 60, borderRadius: 30, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 6 },
    agendaGuideOverlay: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      zIndex: 90,
      backgroundColor: colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 24,
    },
    agendaGuideCard: {
      width: '100%',
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.borderLight,
      padding: 22,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.22,
      shadowRadius: 24,
      elevation: 14,
    },
    agendaGuideCloseButton: {
      position: 'absolute',
      top: 14,
      right: 14,
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.inputBg,
      zIndex: 1,
    },
    agendaGuideIconCircle: {
      width: 70,
      height: 70,
      borderRadius: 35,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginTop: 6,
      marginBottom: 16,
    },
    agendaGuideEyebrow: {
      color: colors.primary,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      textAlign: 'center',
      marginBottom: 8,
    },
    agendaGuideTitle: { color: colors.text, fontSize: 23, fontWeight: '800', textAlign: 'center', marginBottom: 10 },
    agendaGuideText: { color: colors.textSecondary, fontSize: 14, lineHeight: 22, textAlign: 'center', marginBottom: 16 },
    agendaGuideList: { gap: 10, marginBottom: 18 },
    agendaGuideListItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBg,
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    agendaGuideListText: { color: colors.text, fontSize: 13, fontWeight: '600', lineHeight: 18, marginLeft: 8, flex: 1 },
    patientsHeroSection: { paddingTop: 8, marginBottom: 10 },
    pageTitlePacientes: { color: colors.text, fontSize: 24, fontWeight: '700', textAlign: 'center', marginBottom: 8 },
    pageSubtitlePacientes: { color: colors.textSecondary, fontSize: 14, textAlign: 'center', marginBottom: 18 },
    patientsSearchBar: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.background,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 28,
      paddingHorizontal: 20,
      height: 56,
      marginBottom: 22,
    },
    patientsSearchInput: { flex: 1, color: colors.textSecondary, marginLeft: 12, fontSize: 14, fontWeight: '500' },
    patientsActionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 28 },
    patientActionPill: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 92,
      height: 44,
      paddingHorizontal: 16,
      borderRadius: 22,
      backgroundColor: 'rgba(59,130,246,0.03)',
      borderWidth: 1,
      borderColor: colors.primary,
      flexShrink: 1,
    },
    patientActionPillText: { color: colors.primary, fontSize: 12, fontWeight: '700', marginLeft: 7 },
    filterRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18, backgroundColor: colors.surface, borderRadius: 16, paddingHorizontal: 16, paddingVertical: 13 },
    filterLabel: { color: colors.text, fontSize: 14, fontWeight: '600' },
    patientCard: { backgroundColor: colors.surface, borderRadius: 18, padding: 16, marginBottom: 14, borderWidth: 1, borderColor: colors.borderLight },
    patientCardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
    patientNameRow: { flexDirection: 'row', alignItems: 'center', flex: 1 },
    patientNameContent: { marginLeft: 10, flexShrink: 1, paddingRight: 10 },
    patientNameText: { color: colors.text, fontSize: 17, fontWeight: '700' },
    patientMiniInfo: { color: colors.textSecondary, fontSize: 12, marginTop: 2 },
    patientHeaderActions: { width: 126, height: 32, justifyContent: 'center', alignItems: 'flex-end', position: 'relative' },
    patientMoreButtonLayer: { position: 'absolute', right: 0 },
    patientMoreButton: { width: 32, height: 32, borderRadius: 16, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.inputBg },
    patientMenu: { position: 'absolute', top: 30, right: 0, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingVertical: 6, minWidth: 160, zIndex: 20 },
    patientMenuItem: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 12 },
    patientMenuText: { color: colors.text, fontSize: 14, fontWeight: '600', marginLeft: 10 },
    smallActionPill: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primaryLight, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 999, marginRight: 8 },
    smallActionPillText: { color: colors.primaryText, fontSize: 12, fontWeight: '700', marginLeft: 6 },
    patientRecordsContainer: { marginTop: 4 },
    patientRecordItem: { paddingVertical: 10 },
    patientRecordHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    patientRecordInfoCol: { flex: 1, paddingRight: 10 },
    patientRecordBorder: { borderBottomWidth: 1, borderBottomColor: colors.borderLight },
    patientDetailRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
    patientDetailText: { color: colors.textSecondary, marginLeft: 8, fontSize: 13 },
    patientEvalEditBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primaryLight,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(59,130,246,0.3)',
      paddingVertical: 6,
      paddingHorizontal: 10,
      minHeight: 30,
    },
    patientEvalEditText: { color: colors.primary, fontSize: 12, fontWeight: '700', marginLeft: 5 },
    archivedSectionTitle: { color: colors.textSecondary, fontSize: 14, fontWeight: '700', marginTop: 8, marginBottom: 12, textTransform: 'uppercase', letterSpacing: 0.6 },
    archivedInfoText: { color: colors.textSecondary, fontSize: 13 },
    accordionHeader: { backgroundColor: colors.surface, borderRadius: 16, paddingHorizontal: 16, paddingVertical: 18, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: colors.borderLight },
    accordionHeaderActive: { borderColor: colors.primary },
    accordionTitleRow: { flexDirection: 'row', alignItems: 'center', flex: 1, paddingRight: 10 },
    accordionTitleText: { color: colors.text, fontSize: 15, fontWeight: '700', marginLeft: 10, flexShrink: 1 },
    accordionContent: { backgroundColor: colors.surface, borderRadius: 16, padding: 16, marginTop: -2, marginBottom: 12, borderWidth: 1, borderColor: colors.borderLight },
    formRow: { flexDirection: 'row', gap: 10, marginBottom: 10 },
    formCol: { flex: 1 },
    formLabel: { color: colors.text, fontSize: 13, fontWeight: '700', marginBottom: 8 },
    formInput: { backgroundColor: colors.inputBg, borderRadius: 12, borderWidth: 1, borderColor: colors.borderLight, paddingHorizontal: 14, height: 48, color: colors.text, fontSize: 14 },
    inputWithIcon: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.inputBg, borderRadius: 12, borderWidth: 1, borderColor: colors.borderLight, paddingHorizontal: 14, minHeight: 48 },
    formInputFlex: { flex: 1, color: colors.text, fontSize: 14, paddingVertical: 14 },
    inputWithIconFlex: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.inputBg, borderRadius: 12, borderWidth: 1, borderColor: colors.borderLight, paddingHorizontal: 14, minHeight: 48 },
    dropdownContainer: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 12, marginTop: 6, overflow: 'hidden' },
    dropdownItem: { paddingHorizontal: 14, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.borderLight },
    dropdownText: { color: colors.text, fontSize: 14 },
    checkboxContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    checkboxLabel: { color: colors.text, fontSize: 14, marginLeft: 10, flex: 1 },
    checkboxLabelList: { color: colors.text, fontSize: 14, marginLeft: 10, flex: 1 },
    exportCardsRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
    exportCard: { flex: 1, backgroundColor: colors.surface, borderRadius: 16, padding: 18, alignItems: 'center', borderWidth: 1, borderColor: colors.borderLight },
    exportCardSelected: { borderColor: colors.primary, backgroundColor: colors.primaryLight },
    exportCardText: { color: colors.text, fontSize: 13, fontWeight: '700', marginTop: 8 },
    selectPatientPill: { paddingVertical: 9, paddingHorizontal: 14, borderRadius: 999, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderLight, marginRight: 10 },
    selectPatientText: { color: colors.text, fontSize: 13, fontWeight: '700' },
    btnSalvarAvaliacao: { backgroundColor: '#3B82F6', height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', marginTop: 10, marginBottom: 18 },
    chatContainer: { flex: 1, backgroundColor: colors.background },
    chatHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: Platform.OS === 'android' ? Math.max((StatusBar.currentHeight || 0) + 10, 34) : 18, paddingBottom: 10 },
    btnVoltarChat: { width: 40, height: 40, justifyContent: 'center' },
    btnInfoChat: { width: 40, height: 40, justifyContent: 'center', alignItems: 'flex-end' },
    chatContent: { flex: 1, paddingHorizontal: 20 },
    chatContentEmpty: { flexGrow: 1 },
    chatContentFilled: { paddingTop: 8, paddingBottom: 20 },
    chatEmptyState: { flexGrow: 1, justifyContent: 'flex-end', paddingBottom: 26 },
    chatMessagesWrap: { paddingBottom: 20 },
    chatGreeting: { color: colors.text, fontSize: 28, fontWeight: '700', lineHeight: 34, marginBottom: 12 },
    chatGreetingSubtext: { color: colors.textSecondary, fontSize: 14, lineHeight: 22, marginBottom: 24, maxWidth: '92%' },
    chatSuggestionsRow: { flexDirection: 'row', gap: 12 },
    chatSuggestionCard: { flex: 1, backgroundColor: colors.surface, borderRadius: 18, padding: 16, minHeight: 116, justifyContent: 'space-between', borderWidth: 1, borderColor: colors.borderLight },
    chatSuggestionTitle: { color: colors.text, fontSize: 15, fontWeight: '700' },
    chatSuggestionText: { color: colors.textSecondary, fontSize: 13, marginTop: 8 },
    msgUser: { alignSelf: 'flex-end', backgroundColor: colors.primary, paddingHorizontal: 14, paddingVertical: 12, borderRadius: 18, borderBottomRightRadius: 6, marginBottom: 10, maxWidth: '80%' },
    msgAi: { alignSelf: 'flex-start', backgroundColor: colors.surface, paddingHorizontal: 14, paddingVertical: 12, borderRadius: 18, borderBottomLeftRadius: 6, marginBottom: 10, maxWidth: '84%' },
    msgUserText: { color: '#FFF', fontSize: 14, lineHeight: 20 },
    msgAiText: { color: colors.text, fontSize: 14, lineHeight: 20 },
    chatInputArea: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: Platform.OS === 'android' ? 46 : 18, borderTopWidth: 1, borderTopColor: colors.borderLight },
    chatTopicRow: { paddingBottom: 12, paddingRight: 10 },
    chatTopicChip: { height: 34, borderRadius: 17, backgroundColor: colors.primaryLight, borderWidth: 1, borderColor: 'rgba(59,130,246,0.28)', justifyContent: 'center', paddingHorizontal: 14, marginRight: 8 },
    chatTopicChipText: { color: colors.primary, fontSize: 12, fontWeight: '700' },
    chatInputBoxImageStyle: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: 18, paddingLeft: 14, paddingRight: 8, minHeight: 56 },
    chatInputField: { flex: 1, color: colors.text, fontSize: 15, paddingVertical: 14, marginRight: 10 },
    btnSendChatIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.primary, justifyContent: 'center', alignItems: 'center' },
    chatDisclaimer: { color: colors.textSecondary, fontSize: 11, textAlign: 'center', marginTop: 10 },
    chatInfoScrollContent: { paddingBottom: 40 },
    chatInfoHeroCard: { backgroundColor: '#0F3D91', borderRadius: 28, padding: 24, marginTop: 8, marginBottom: 22, overflow: 'hidden' },
    chatInfoHeroOrbLarge: { position: 'absolute', width: 180, height: 180, borderRadius: 90, backgroundColor: 'rgba(255,255,255,0.08)', top: -72, right: -34 },
    chatInfoHeroOrbSmall: { position: 'absolute', width: 112, height: 112, borderRadius: 56, backgroundColor: 'rgba(191,219,254,0.18)', bottom: -26, right: 34 },
    chatInfoBadge: { alignSelf: 'flex-start', backgroundColor: 'rgba(191,219,254,0.16)', borderRadius: 999, borderWidth: 1, borderColor: 'rgba(191,219,254,0.2)', paddingVertical: 8, paddingHorizontal: 12, marginBottom: 18 },
    chatInfoBadgeText: { color: '#DBEAFE', fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.4 },
    chatInfoHeroTitle: { color: '#FFF', fontSize: 30, fontWeight: '800', lineHeight: 36, marginBottom: 12, maxWidth: '82%' },
    chatInfoHeroText: { color: '#DBEAFE', fontSize: 15, lineHeight: 24, maxWidth: '90%' },
    chatInfoSectionTitle: { color: colors.text, fontSize: 24, fontWeight: '800', marginBottom: 14 },
    chatInfoCardsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 8 },
    chatInfoCard: { width: '48%', backgroundColor: colors.surface, borderRadius: 24, borderWidth: 1, borderColor: 'rgba(59,130,246,0.18)', padding: 18, minHeight: 190, marginBottom: 14 },
    chatInfoIconWrap: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.primaryLight, justifyContent: 'center', alignItems: 'center', marginBottom: 14 },
    chatInfoCardTitle: { color: colors.text, fontSize: 16, fontWeight: '700', lineHeight: 22, marginBottom: 10 },
    chatInfoCardText: { color: colors.textSecondary, fontSize: 14, lineHeight: 22 },
    chatInfoNotice: { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: colors.surface, borderRadius: 20, borderWidth: 1, borderColor: colors.borderLight, padding: 16, marginBottom: 24 },
    chatInfoNoticeText: { flex: 1, color: colors.textSecondary, fontSize: 13, lineHeight: 21, marginLeft: 12 },
    chatInfoDivider: { height: 1, backgroundColor: colors.borderLight, marginBottom: 24 },
    chatInfoSupportText: { color: colors.textSecondary, fontSize: 15, lineHeight: 24, marginBottom: 20 },
    chatInfoPrimaryButton: { height: 56, borderRadius: 28, backgroundColor: '#2563EB', justifyContent: 'center', alignItems: 'center', flexDirection: 'row', marginBottom: 12 },
    chatInfoPrimaryButtonText: { color: '#FFF', fontSize: 16, fontWeight: '700', marginLeft: 8 },
    chatInfoSecondaryButton: { height: 56, borderRadius: 28, backgroundColor: colors.primaryLight, borderWidth: 1, borderColor: 'rgba(59,130,246,0.25)', justifyContent: 'center', alignItems: 'center', flexDirection: 'row' },
    chatInfoSecondaryButtonText: { color: colors.primary, fontSize: 16, fontWeight: '700', marginLeft: 8 },
    profileHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 24, marginTop: Platform.OS === 'android' ? Math.max((StatusBar.currentHeight || 0) + 10, 34) : 24, marginBottom: 22 },
    profileHeaderSideSpacer: { width: 50 },
    profileHeaderTitle: { color: colors.text, fontSize: 26, fontWeight: '800' },
    profileSettingsBtn: { padding: 4, width: 50, alignItems: 'flex-end' },
    profileSettingsIconBox: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.surface, justifyContent: 'center', alignItems: 'center' },
    profileInfoContainer: { alignItems: 'center', marginBottom: 30 },
    profileAvatarWrapper: { width: 104, height: 104, borderRadius: 52, backgroundColor: colors.avatarBg, justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
    profileAvatarInner: { width: 90, height: 90, borderRadius: 45, justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
    profileAvatarEditBadge: {
      position: 'absolute',
      right: 6,
      bottom: 8,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: '#3B82F6',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: colors.surface,
    },
    profileAvatarHint: { color: colors.textSecondary, fontSize: 12, marginTop: -2, marginBottom: 8 },
    profileAvatarTextLarge: { color: colors.text, fontSize: 28, fontWeight: '700' },
    profileNameText: { color: colors.text, fontSize: 26, fontWeight: '800', marginBottom: 6, textAlign: 'center' },
    profileEmailText: { color: colors.textSecondary, fontSize: 15, textAlign: 'center' },
    metricsCard: { backgroundColor: colors.surface, borderRadius: 18, padding: 18, marginBottom: 24 },
    metricsHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
    metricsTitle: { color: colors.text, fontSize: 16, fontWeight: '700', marginLeft: 8 },
    metricsRow: { flexDirection: 'row', justifyContent: 'space-between' },
    metricCol: { flex: 1, alignItems: 'center' },
    metricValue: { fontSize: 28, fontWeight: '800', marginBottom: 6, textAlign: 'center' },
    metricLabel: { color: colors.textSecondary, fontSize: 12, textAlign: 'center', lineHeight: 16 },
    profileSectionTitle: { color: colors.textSecondary, fontSize: 12, fontWeight: '800', letterSpacing: 0.8, marginBottom: 12 },
    profileMenuItem: { backgroundColor: colors.surface, borderRadius: 18, padding: 16, flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    profileMenuItemDanger: { borderWidth: 1, borderColor: 'rgba(239, 68, 68, 0.2)' },
    profileMenuSpacer: { height: 6 },
    menuIconBox: { width: 42, height: 42, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    menuTextCol: { flex: 1 },
    menuTitle: { color: colors.text, fontSize: 15, fontWeight: '700', marginBottom: 2 },
    menuSubtitle: { color: colors.textSecondary, fontSize: 12 },
    menuTitleDanger: { color: '#EF4444' },
    settingsRowDisabled: { opacity: 0.58 },
    settingsHeroCard: {
      backgroundColor: colors.surface,
      borderRadius: 22,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.borderLight,
      marginBottom: 18,
    },
    settingsHeroIcon: {
      width: 54,
      height: 54,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 14,
    },
    settingsHeroTitle: { color: colors.text, fontSize: 22, fontWeight: '800', marginBottom: 8 },
    settingsHeroText: { color: colors.textSecondary, fontSize: 14, lineHeight: 22 },
    settingsInfoCard: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.borderLight,
      marginBottom: 12,
    },
    settingsInfoHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    settingsInfoTitle: { color: colors.text, fontSize: 15, fontWeight: '700', marginLeft: 8 },
    settingsInfoText: { color: colors.textSecondary, fontSize: 13, lineHeight: 21 },
    aboutHeroCard: {
      backgroundColor: colors.surface,
      borderRadius: 22,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.borderLight,
      marginBottom: 18,
    },
    aboutBrandRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
    aboutBrandLogo: { width: 60, height: 60, marginRight: 12 },
    aboutBrandTitle: { color: colors.text, fontSize: 24, fontWeight: '800', marginBottom: 4 },
    aboutBrandSubtitle: { color: colors.textSecondary, fontSize: 13, lineHeight: 20 },
    aboutVersionPill: {
      alignSelf: 'flex-start',
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.primaryLight,
      borderWidth: 1,
      borderColor: 'rgba(59,130,246,0.25)',
    },
    aboutVersionPillText: { color: colors.primary, fontSize: 12, fontWeight: '700' },
    relatorioHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 24, marginTop: Platform.OS === 'android' ? Math.max((StatusBar.currentHeight || 0) + 10, 34) : 22, marginBottom: 16 },
    relatorioHeaderTitle: { color: colors.text, fontSize: 22, fontWeight: '700' },
    emptyStateCard: { backgroundColor: colors.surface, borderRadius: 18, padding: 24, alignItems: 'center', marginTop: 10 },
    emptyStateTitle: { color: colors.text, fontSize: 17, fontWeight: '700', marginTop: 12, marginBottom: 6 },
    emptyStateText: { color: colors.textSecondary, fontSize: 13, textAlign: 'center', lineHeight: 20 },
    modalListItem: { width: '100%', backgroundColor: colors.inputBg, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 14, marginBottom: 10, borderWidth: 1, borderColor: colors.borderLight },
    modalListTitle: { color: colors.text, fontSize: 15, fontWeight: '700' },
    modalListSubtitle: { color: colors.textSecondary, fontSize: 12, marginTop: 4 },
    reportHeaderCard: { backgroundColor: colors.surface, borderRadius: 18, padding: 18, marginBottom: 14 },
    reportPatientName: { color: colors.text, fontSize: 20, fontWeight: '800', marginBottom: 4 },
    reportPatientMeta: { color: colors.textSecondary, fontSize: 13, lineHeight: 18 },
    reportStatsRow: { flexDirection: 'row', gap: 12, marginBottom: 14 },
    reportStatCard: { flex: 1, backgroundColor: colors.surface, borderRadius: 16, padding: 16 },
    reportStatValue: { color: colors.primary, fontSize: 16, fontWeight: '800', marginBottom: 4 },
    reportStatLabel: { color: colors.textSecondary, fontSize: 12 },
    compareHeaderRow: { flexDirection: 'row', gap: 12, marginVertical: 14 },
    compareColHeader: { flex: 1, backgroundColor: colors.surface, borderRadius: 16, padding: 14 },
    compareColTitle: { color: colors.text, fontSize: 14, fontWeight: '800', marginBottom: 4 },
    compareColSub: { color: colors.textSecondary, fontSize: 12 },
    compareRow: { backgroundColor: colors.surface, borderRadius: 16, padding: 14, marginBottom: 10 },
    compareRowLabel: { color: colors.text, fontSize: 13, fontWeight: '800', marginBottom: 10 },
    compareValueWrap: { backgroundColor: colors.inputBg, borderRadius: 12, padding: 12, marginBottom: 8 },
    compareValue: { color: colors.textSecondary, fontSize: 13 },
    headerBrandRow: { flexDirection: 'row', alignItems: 'center' },
    homeScrollContent: { paddingBottom: 20, paddingTop: 4 },
    homeSearchPill: { height: 56, borderRadius: 28, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.background, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', marginTop: 8, marginBottom: 22 },
    homeSearchText: { color: colors.textSecondary, fontSize: 17, marginLeft: 12, fontWeight: '500' },
    homeHeroCard: { backgroundColor: colors.surface, borderRadius: 20, paddingHorizontal: 20, paddingVertical: 22, marginBottom: 18, borderWidth: 1, borderColor: colors.borderLight },
    homeHeroTitle: { color: colors.text, fontSize: 22, fontWeight: '800', marginBottom: 8 },
    homeHeroSubtitle: { color: colors.textSecondary, fontSize: 15, lineHeight: 22 },
    homeQuickPills: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 28 },
    homeQuickPill: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', minWidth: 92, paddingHorizontal: 16, height: 44, borderRadius: 22, backgroundColor: colors.primaryLight },
    homeQuickPillText: { color: colors.primary, fontSize: 12, fontWeight: '700', marginLeft: 7 },
    homeSectionHeading: { color: colors.text, fontSize: 18, fontWeight: '800', marginBottom: 14 },
    homeStatsGrid: { flexDirection: 'row', gap: 18, marginBottom: 26, paddingHorizontal: 2 },
    homeStatMinimal: { flex: 1, minHeight: 96, flexDirection: 'column', justifyContent: 'center', alignItems: 'center', gap: 6 },
    homeStatNumber: { color: colors.text, fontSize: 42, fontWeight: '800', lineHeight: 42 },
    homeStatCaption: { color: colors.textSecondary, fontSize: 13 },
    homeShortcutGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
    homeShortcutCard: { width: '48%', aspectRatio: 1, backgroundColor: colors.surface, borderRadius: 20, borderWidth: 1, borderColor: colors.borderLight, marginBottom: 14, padding: 18, justifyContent: 'center', alignItems: 'center' },
    homeShortcutText: { color: colors.text, fontSize: 15, fontWeight: '700', textAlign: 'center', marginTop: 16 },
    patientInlineIconActions: {
      position: 'absolute',
      right: 0,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 8,
    },
    patientIconActionBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.inputBg,
    },

    // ESTILOS BARRA TECIDOS E DOR
    tissueBarContainer: { height: 12, borderRadius: 6, flexDirection: 'row', overflow: 'hidden', marginTop: 12, marginBottom: 12, backgroundColor: colors.borderLight },
    tissueBarSegment: { height: '100%' },
    tissueLegendRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 15 },
    tissueLegendItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
    tissueLegendDot: { width: 10, height: 10, borderRadius: 5, marginRight: 6 },
    tissueLegendText: { color: colors.textSecondary, fontSize: 11, fontWeight: '600' },
    painScaleBar: { flexDirection: 'row', height: 44, borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: colors.borderLight },
    painScaleSegment: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    painScaleText: { color: colors.textSecondary, fontSize: 13, fontWeight: '700' },

    // ESTILOS IMAGE PICKER (AVALIAÇÃO - FERIDA)
    imagePickerArea: { backgroundColor: colors.inputBg, borderRadius: 12, borderWidth: 1.5, borderColor: colors.border, borderStyle: 'dashed', overflow: 'hidden', marginBottom: 5 },
    imagePickerPlaceholder: { alignItems: 'center', justifyContent: 'center', paddingVertical: 35 },
    imagePickerIconCircle: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.primaryLight, justifyContent: 'center', alignItems: 'center' },
    imagePreviewContainer: { position: 'relative' },
    imagePreview: { width: '100%', height: 220, borderRadius: 10, backgroundColor: colors.inputBg },
    imageOverlayBadge: { position: 'absolute', top: 10, left: 10, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.7)', paddingVertical: 5, paddingHorizontal: 10, borderRadius: 20 },
    imageRoiBadge: { position: 'absolute', top: 48, left: 10, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(16, 185, 129, 0.16)', borderWidth: 1, borderColor: 'rgba(16, 185, 129, 0.45)', paddingVertical: 5, paddingHorizontal: 10, borderRadius: 20 },
    imageChangeBtn: { position: 'absolute', bottom: 10, left: 10, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(59, 130, 246, 0.9)', paddingVertical: 7, paddingHorizontal: 12, borderRadius: 20 },
    imageRemoveBtn: { position: 'absolute', bottom: 10, right: 10, width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(239, 68, 68, 0.2)', justifyContent: 'center', alignItems: 'center' },
    imagePickerOption: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.inputBg, borderRadius: 12, padding: 16, marginBottom: 12, width: '100%' },
    imagePickerIconBox: { width: 50, height: 50, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
    roiToolsRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 10, marginBottom: 6 },
    roiToolButton: { flex: 1, minHeight: 44, borderRadius: 14, backgroundColor: colors.primaryLight, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
    roiToolButtonText: { color: colors.primary, fontSize: 13, fontWeight: '800', marginLeft: 6 },
    roiStatusPill: { minHeight: 38, borderRadius: 19, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.borderLight, backgroundColor: colors.inputBg },
    roiStatusText: { color: colors.textSecondary, fontSize: 12, fontWeight: '700', marginLeft: 5 },
    roiEditorScreen: { flex: 1, backgroundColor: colors.background },
    roiEditorHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingTop: Platform.OS === 'android' ? Math.max((StatusBar.currentHeight || 0) + 8, 24) : 8, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: colors.borderLight },
    roiHeaderButton: { minWidth: 84, minHeight: 40, flexDirection: 'row', alignItems: 'center' },
    roiHeaderButtonText: { color: colors.text, fontSize: 13, fontWeight: '800', marginLeft: 4 },
    roiEditorTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
    roiEditorBody: { flex: 1, paddingHorizontal: 18 },
    roiEditorBodyContent: { paddingTop: 16, paddingBottom: 16 },
    roiImageStage: { width: '100%', aspectRatio: 3 / 4, maxHeight: 520, minHeight: 360, borderRadius: 18, overflow: 'hidden', backgroundColor: colors.inputBg, borderWidth: 1, borderColor: colors.borderLight, position: 'relative' },
    roiEditorImage: { width: '100%', height: '100%' },
    roiEditorHintCard: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, backgroundColor: colors.surface, borderRadius: 16, padding: 14, borderWidth: 1, borderColor: colors.borderLight, marginTop: 14 },
    roiEditorHintTitle: { color: colors.text, fontSize: 14, fontWeight: '800', marginBottom: 3 },
    roiEditorHintText: { color: colors.textSecondary, fontSize: 12, lineHeight: 18 },
    roiModeRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
    roiModeButton: { flex: 1, minHeight: 42, borderRadius: 21, borderWidth: 1, borderColor: colors.borderLight, backgroundColor: colors.inputBg, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
    roiModeButtonActive: { backgroundColor: colors.primary, borderColor: colors.primary },
    roiModeButtonText: { color: colors.primary, fontSize: 12, fontWeight: '800', marginLeft: 6 },
    roiModeButtonTextActive: { color: '#FFF' },
    roiPreviewRow: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
    roiPreviewPill: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.inputBg, borderWidth: 1, borderColor: colors.borderLight, borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8 },
    roiPreviewText: { color: colors.textSecondary, fontSize: 12, fontWeight: '700', marginLeft: 6 },
    roiAddButton: { marginLeft: 'auto', minHeight: 36, borderRadius: 18, backgroundColor: colors.primaryLight, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12 },
    roiAddButtonText: { color: colors.primary, fontSize: 12, fontWeight: '800', marginLeft: 4 },
    roiListScroll: { marginTop: 10, maxHeight: 48 },
    roiChip: { height: 38, borderRadius: 19, borderWidth: 1, borderColor: colors.borderLight, backgroundColor: colors.inputBg, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, marginRight: 8 },
    roiChipDot: { width: 9, height: 9, borderRadius: 5, marginRight: 6 },
    roiChipText: { color: colors.text, fontSize: 12, fontWeight: '800' },
    roiChipCount: { color: colors.textSecondary, fontSize: 11, fontWeight: '800', marginLeft: 6 },
    roiSmallActionsRow: { flexDirection: 'row', gap: 10, marginTop: 10 },
    roiSmallActionButton: { flex: 1, minHeight: 36, borderRadius: 18, borderWidth: 1, borderColor: colors.borderLight, backgroundColor: colors.inputBg, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
    roiSmallActionText: { color: colors.textSecondary, fontSize: 12, fontWeight: '800', marginLeft: 5 },
    roiEditorFooter: { flexDirection: 'row', gap: 12, paddingHorizontal: 18, paddingTop: 12, paddingBottom: Platform.OS === 'android' ? 42 : 20, borderTopWidth: 1, borderTopColor: colors.borderLight },
    roiSecondaryButton: { flex: 1, height: 52, borderRadius: 26, backgroundColor: colors.inputBg, borderWidth: 1, borderColor: colors.borderLight, justifyContent: 'center', alignItems: 'center' },
    roiSecondaryButtonText: { color: colors.text, fontSize: 15, fontWeight: '800' },
    roiPrimaryButton: { flex: 1.4, height: 52, borderRadius: 26, backgroundColor: colors.primary, justifyContent: 'center', alignItems: 'center' },
    roiPrimaryButtonText: { color: '#FFF', fontSize: 15, fontWeight: '800' },
    compareCard: { flex: 1, backgroundColor: colors.surface, borderRadius: 16, padding: 14, alignItems: 'center', borderWidth: 1, borderColor: colors.borderLight },
    compareBadge: { paddingHorizontal: 12, paddingVertical: 4, borderRadius: 8, marginBottom: 16, alignSelf: 'center' },
    compareBadgeText: { fontSize: 11, fontWeight: '800', letterSpacing: 0.5 },
    compareImagePlaceholder: { width: '100%', aspectRatio: 1, backgroundColor: colors.inputBg, borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginBottom: 12, overflow: 'hidden', position: 'relative' },
    compareCardDate: { color: colors.textSecondary, fontSize: 13, marginBottom: 16, fontWeight: '500' },
    compareCardStatRow: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginBottom: 8 },
    compareCardStatLabel: { color: colors.textSecondary, fontSize: 12, fontWeight: '500' },
    compareCardStatValue: { color: colors.text, fontSize: 14, fontWeight: '800' },
    chartContainer: { backgroundColor: colors.surface, borderRadius: 16, padding: 18, marginBottom: 25, borderWidth: 1, borderColor: colors.borderLight },
    chartHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    chartTitle: { color: colors.text, fontSize: 16, fontWeight: '700' },
    chartBadgeText: { color: '#10B981', fontSize: 14, fontWeight: 'bold' },
    chartBody: { flexDirection: 'row', height: 120, marginBottom: 10 },
    chartYAxis: { justifyContent: 'space-between', paddingRight: 10, alignItems: 'flex-end', width: 50 },
    chartAxisText: { color: colors.textSecondary, fontSize: 11, fontWeight: '500' },
    chartGrid: { flex: 1, position: 'relative', justifyContent: 'space-between' },
    chartGridLine: { height: 1, backgroundColor: colors.borderLight },
    chartGradientArea: { position: 'absolute', bottom: 0, left: 0, right: 0, height: '70%', backgroundColor: 'rgba(16, 185, 129, 0.15)', borderTopLeftRadius: 0, borderTopRightRadius: 0 },
    chartLineSegment: { position: 'absolute', height: 2, backgroundColor: '#10B981' },
    chartDot: { position: 'absolute', width: 10, height: 10, borderRadius: 5, backgroundColor: '#10B981', borderWidth: 2, borderColor: colors.surface, transform: [{translateX: -5}, {translateY: -5}] },
    chartXAxis: { flexDirection: 'row', justifyContent: 'space-between', paddingLeft: 50, paddingRight: 5 },
    comparativoClinicoContainer: { backgroundColor: colors.surface, borderRadius: 16, paddingHorizontal: 18, paddingVertical: 10, marginBottom: 25, borderWidth: 1, borderColor: colors.borderLight },
    comparativoRow: { paddingVertical: 14 },
    comparativoLabelTop: { color: colors.textSecondary, fontSize: 12, fontWeight: '600', marginBottom: 6 },
    comparativoValRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
    comparativoValTextRowLeft: { fontSize: 13, fontWeight: '700', flex: 1, textAlign: 'center', paddingRight: 10, color: '#EF4444' },
    comparativoValTextRowRight: { fontSize: 13, fontWeight: '700', flex: 1, textAlign: 'center', paddingLeft: 10, color: '#10B981' },
    comparativoDivider: { height: 1, backgroundColor: colors.borderLight },
    btnExportarPdfComparativo: { backgroundColor: '#3B82F6', borderRadius: 28, height: 56, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: 20 },
    btnExportarPdfText: { color: '#FFF', fontSize: 16, fontWeight: '700', marginLeft: 8 },
    reportImagePreviewCard: { backgroundColor: colors.surface, borderRadius: 16, padding: 14, borderWidth: 1, borderColor: colors.borderLight, marginBottom: 16 },
    reportImagePreviewTitle: { color: colors.text, fontSize: 14, fontWeight: '800', marginBottom: 10 },
    reportImagePreviewFrame: { height: 190, borderRadius: 12, overflow: 'hidden', backgroundColor: colors.inputBg, position: 'relative' },
    reportImagePreview: { width: '100%', height: '100%' },
    reportImageMeta: { color: colors.textSecondary, fontSize: 12, fontWeight: '700', marginTop: 8 },
    evalSequenceScroll: { marginBottom: 22 },
    evalSequenceCard: { width: 168, backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.borderLight, padding: 12, marginRight: 12 },
    evalSequenceImage: { width: '100%', aspectRatio: 1.18, borderRadius: 12, overflow: 'hidden', backgroundColor: colors.inputBg, alignItems: 'center', justifyContent: 'center', marginBottom: 10, position: 'relative' },
    patientEvalThumb: { width: 72, height: 72, borderRadius: 12, overflow: 'hidden', backgroundColor: colors.inputBg, alignItems: 'center', justifyContent: 'center', marginRight: 12, position: 'relative' },
    evalSequenceTitle: { color: colors.text, fontSize: 13, fontWeight: '800', marginBottom: 4 },
    evalSequenceMeta: { color: colors.textSecondary, fontSize: 11, lineHeight: 16 },
    evalSequenceActions: { flexDirection: 'row', gap: 8, marginTop: 10 },
    evalSequenceButton: { flex: 1, minHeight: 34, borderRadius: 17, backgroundColor: colors.inputBg, borderWidth: 1, borderColor: colors.borderLight, alignItems: 'center', justifyContent: 'center' },
    evalSequenceButtonText: { color: colors.primary, fontSize: 11, fontWeight: '800' },
    chartLegendRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
    chartLegendPill: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.inputBg, borderRadius: 14, paddingHorizontal: 10, paddingVertical: 6 },
    chartLegendDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },
    chartLegendText: { color: colors.textSecondary, fontSize: 11, fontWeight: '700' },
  });
}

export default getStyles;
